parameters:
#    blogger_blog_cours_ihm.example.class: Blogger\BlogCoursIhmBundle\Example

services:
#    blogger_blog_cours_ihm.example:
#        class: %blogger_blog_cours_ihm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
