#parameters:
#    blogger_blog_cours_ihm.example.class: Blogger\BlogCoursIhmBundle\Example
#
services:
    blogger_blog_cours_ihm.Article:
        class: Blogger\BlogCoursIhmBundle\Entity\Article
        arguments: ['titre', 'auteur', 'mon contenu....']
    blogger_blog_cours_ihm.Comment:
        class: Blogger\BlogCoursIhmBundle\Entity\Comment
         
#    blogger_blog_cours_ihm.example:
#        class: %blogger_blog_cours_ihm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
